//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "refinery_schema_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub version: i32,
    pub name: Option<String>,
    pub applied_on: Option<String>,
    pub checksum: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
