//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "statuses")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        unique_key = "uq_status_id_project"
    )]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    pub weight: i32,
    #[sea_orm(unique_key = "uq_status_id_project")]
    pub project_id: Uuid,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub archived_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub issues: HasMany<super::issues::Entity>,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub projects: HasOne<super::projects::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
