//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub fullname: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub role: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub archived_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub issues: HasMany<super::issues::Entity>,
    #[sea_orm(has_many, via = "projects_to_users")]
    pub projects: HasMany<super::projects::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
